import { StyleSheet } from "react-native";
import { colors } from "../../../shared/theme/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  balanceCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 16,
    padding: 20,
    borderRadius: 16,
  },
  balanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  balanceLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  availableBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    gap: 2,
  },
  availableText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.positive,
  },
  balanceLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.text.tertiary,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  balanceAmount: {
    fontSize: 40,
    fontWeight: "700",
    color: colors.text.primary,
    marginBottom: 8,
    letterSpacing: -1.5,
  },
  changeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  currencyBadge: {
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  currencyText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.text.tertiary,
  },
  changeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  changeText: {
    fontSize: 13,
    fontWeight: "600",
  },
  positive: {
    color: colors.positive,
  },
  negative: {
    color: colors.negative,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    fontWeight: "bold",
    color: colors.text.secondary,
  },
  seeAllButton: {
    color: colors.primary,
    fontWeight: "600",
  },
  topMoversContainer: {
    paddingHorizontal: 20,
    gap: 12,
  },
  activityContainer: {
    backgroundColor: colors.background.card,
    marginHorizontal: 20,
    borderRadius: 16,
    overflow: "hidden",
  },
  clearButton: {
    backgroundColor: colors.negative,
    marginHorizontal: 20,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  clearButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyActivityContainer: {
    backgroundColor: colors.background.card,
    marginHorizontal: 20,
    borderRadius: 16,
    paddingVertical: 48,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyActivityTitle: {
    color: colors.text.secondary,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyActivityMessage: {
    color: colors.text.quaternary,
    textAlign: "center",
  },
  favoritesContainer: {
    backgroundColor: colors.background.card,
    marginHorizontal: 20,
    borderRadius: 16,
    overflow: "hidden",
  },
  emptyFavoritesContainer: {
    backgroundColor: colors.background.card,
    marginHorizontal: 20,
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyFavoritesTitle: {
    color: colors.text.secondary,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 4,
  },
  emptyFavoritesMessage: {
    color: colors.text.quaternary,
    textAlign: "center",
    fontSize: 12,
  },
  protectionSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 32,
    paddingVertical: 12,
    gap: 8,
  },
  protectionIcon: {
    marginRight: 4,
  },
  protectionText: {
    fontSize: 11,
    color: colors.text.quaternary,
    textAlign: "center",
    flex: 1,
  },
});
