import { StyleSheet } from 'react-native';
import { colors } from '../../../shared/theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  closeButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
  },
  favoriteButton: {
    padding: 4,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  assetHeader: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  assetIconContainer: {
    marginBottom: 12,
  },
  assetIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  assetIconPlaceholder: {
    backgroundColor: colors.border.medium,
  },
  assetIconText: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text.inverse,
  },
  assetTicker: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text.primary,
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  assetName: {
    fontSize: 13,
    color: colors.text.tertiary,
    marginBottom: 8,
  },
  assetPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  assetPrice: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.text.primary,
  },
  assetChange: {
    fontSize: 14,
    fontWeight: '700',
  },
  changePositive: {
    color: colors.positive,
  },
  changeNegative: {
    color: colors.negative,
  },
  sideToggle: {
    flexDirection: 'row',
    marginBottom: 24,
    gap: 12,
  },
  sideButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  sideButtonActiveBuy: {
    backgroundColor: colors.positiveLight,
    borderColor: colors.positive,
  },
  sideButtonActiveSell: {
    backgroundColor: colors.negativeLight,
    borderColor: colors.negative,
  },
  sideButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  sideButtonTextActive: {
    color: colors.text.primary,
  },
  section: {
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text.quaternary,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  dropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.background.secondary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border.medium,
  },
  dropdownText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.primary,
  },
  dropdownMenu: {
    backgroundColor: colors.background.primary,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border.medium,
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  dropdownItemActive: {
    backgroundColor: colors.background.secondary,
  },
  dropdownItemText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.tertiary,
  },
  dropdownItemTextActive: {
    color: colors.primary,
  },
  inputSection: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text.quaternary,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  quantityInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  quantityInput: {
    flex: 1,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.medium,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
    textAlign: 'center',
  },
  quantityButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.medium,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text.primary,
  },
  amountInputContainer: {
    marginBottom: 12,
  },
  amountInput: {
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.medium,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 12,
  },
  amountInputDisabled: {
    backgroundColor: colors.background.secondary,
    opacity: 0.6,
  },
  percentageChips: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
  },
  percentageChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.medium,
  },
  percentageChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  availableBalanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  availableBalanceLabel: {
    fontSize: 12,
    color: colors.text.quaternary,
    fontWeight: '500',
  },
  availableBalanceAmount: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.positive,
  },
  limitPriceSection: {
    marginBottom: 20,
  },
  limitPriceInput: {
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.medium,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
  },
  inputHint: {
    fontSize: 12,
    color: colors.text.quaternary,
    fontWeight: '500',
    marginTop: 6,
  },
  totalSection: {
    backgroundColor: colors.background.tertiary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  totalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  totalLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text.quaternary,
    letterSpacing: 0.5,
  },
  totalAmount: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.text.primary,
    marginBottom: 16,
    letterSpacing: -1,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  balanceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.positive,
  },
  balanceLabel: {
    fontSize: 13,
    color: colors.text.tertiary,
    fontWeight: '500',
    flex: 1,
  },
  balanceAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text.primary,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.negativeLight,
    borderRadius: 8,
  },
  errorText: {
    fontSize: 13,
    color: colors.negative,
    fontWeight: '600',
    flex: 1,
  },
  swipeButtonContainer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: colors.background.primary,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
});
